import type { CSSProperties, ReactNode } from 'react';

export type ClientPrintBranding = {
  paletteName?: string;
  primary?: string;
  accent?: string;
  logoUrl?: string;
  logoName?: string;
};

function safeHex(value: string | undefined, fallback: string) {
  return /^#[0-9a-fA-F]{6}$/.test(value ?? '') ? value! : fallback;
}

export function ClientPrintHeader({ branding, documentTitle }: { branding?: ClientPrintBranding; documentTitle: string }) {
  const primary = safeHex(branding?.primary, '#030d26');
  const accent = safeHex(branding?.accent, '#1e4fd8');

  const style = { '--client-print-primary': primary, '--client-print-accent': accent } as CSSProperties;

  return <header className="client-print-header" style={style}>
      <div className="client-print-brand">
        {branding?.logoUrl ? (
          <img src={branding.logoUrl} alt={branding.logoName || 'Company logo'} />
        ) : (
          <span className="client-print-brand-fallback">{branding?.paletteName || 'Interview Evaluation'}</span>
        )}
      </div>
      <span className="client-print-document-title">{documentTitle}</span>
    </header>;
}

export function ClientPrintFooter({ branding, documentTitle }: { branding?: ClientPrintBranding; documentTitle: string }) {
  const primary = safeHex(branding?.primary, '#030d26');
  const accent = safeHex(branding?.accent, '#1e4fd8');
  return <footer className="client-print-footer" style={{ '--client-print-primary': primary, '--client-print-accent': accent } as CSSProperties} aria-hidden="true">
      <span>{documentTitle}</span>
      <span>Generated by Stapphire</span>
    </footer>;
}

export function ClientPrintFrame({ branding, documentTitle, children }: { branding?: ClientPrintBranding; documentTitle: string; children: ReactNode }) {
  return <table className="client-print-frame">
    <thead><tr><td><ClientPrintHeader branding={branding} documentTitle={documentTitle} /></td></tr></thead>
    <tbody><tr><td className="client-print-body">{children}</td></tr></tbody>
    <tfoot><tr><td><ClientPrintFooter branding={branding} documentTitle={documentTitle} /></td></tr></tfoot>
  </table>;
}
