import { NextResponse } from 'next/server';
import { supabaseAdmin } from '@/lib/supabaseAdmin';
import { hashJobDescription } from '@/lib/evaluationBasis';
import { HIRING_CRITERIA_EXTRACTOR_VERSION } from '@/lib/hiringCriteriaExtractor';
import { normalizeHiringCriteriaError } from '@/lib/hiringCriteriaError';
import { operationQueue } from '@/lib/operationQueue';
import { markHiringCriteriaDispatchFailed } from '@/lib/operations';
export const runtime='nodejs';
export async function POST(request:Request){try{const body=await request.json();const title=String(body.title||'').trim();const job_description=String(body.job_description||'').trim();if(!title||!job_description)return NextResponse.json({error:'Title and Job Description are required.'},{status:400});const {data,error}=await supabaseAdmin.rpc('create_phase1_requisition_with_evaluation_basis',{p_title:title,p_job_description:job_description,p_job_description_hash:hashJobDescription(job_description)});if(error)throw error;const requisitionId=String(data||'');if(!requisitionId)throw new Error('Requisition creation did not return an ID.');let hiringCriteriaStatus='ready';try{const {data:opData,error:opError}=await supabaseAdmin.rpc('create_phase1_hiring_criteria_operation',{p_requisition_id:requisitionId,p_extractor_version:HIRING_CRITERIA_EXTRACTOR_VERSION});if(opError)throw opError;if(!opData||typeof opData!=='object'||typeof opData.id!=='string'||typeof opData.status!=='string')throw new Error('Hiring Criteria operation creation returned an invalid state.');if(opData.shouldDispatch===true){try{await operationQueue.enqueueHiringCriteria({operationId:opData.id})}catch(dispatchError){await markHiringCriteriaDispatchFailed(opData.id,dispatchError);throw dispatchError}}}catch(extractionError){hiringCriteriaStatus='failed';console.error('Hiring Criteria operation dispatch failed after requisition creation',{requisitionId,error:normalizeHiringCriteriaError(extractionError)})}return NextResponse.json({id:requisitionId,hiring_criteria_status:hiringCriteriaStatus},{status:201})}catch(error){console.error('Requisition creation failed',{error:normalizeHiringCriteriaError(error)});return NextResponse.json({error:'Unable to create requisition. Confirm the Phase 1 SQL has been run.'},{status:500})}}
